# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2022-2030 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_INIT_WATCHDOG) += oplus_bsp_dfr_init_watchdog.o
oplus_bsp_dfr_init_watchdog-y := init_watchdog.o

ccflags-y += -DDYNAMIC_DEBUG_MODULE
