# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2022 Oplus. All rights reserved.

obj-y     += uad/
obj-y     += thermal/
obj-$(CONFIG_OPLUS_OMRG)        += oplus_omrg/
obj-$(CONFIG_OPLUS_FEATURE_ABNORMAL_FLAG) += oplus_overload/
