oplus_sensor_deviceinfo-y := oplus_sensor_devinfo.o
oplus_sensor_deviceinfo-y += oplus_press_cali_info.o
oplus_sensor_deviceinfo-y += oplus_pad_als_info.o
obj-$(CONFIG_OPLUS_FEATURE_SENSOR_CFG) += oplus_sensor_deviceinfo.o
obj-$(CONFIG_SSC_INTERACTIVE) += oplus_ssc_interact/
obj-$(CONFIG_OPLUS_SENSOR_FB_QC) += oplus_sensor_feedback/
