# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2022-2025 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_FDLEAK_CHECK) += oplus_bsp_dfr_fdleak_check.o
oplus_bsp_dfr_fdleak_check-y := oplus_fdleak_check.o
