# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_DUMP_DEVICE_INFO)	+=  oplus_bsp_dfr_dump_device_info.o
oplus_bsp_dfr_dump_device_info-y :=  dump_device_info.o
