# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2021 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_FORCE_SHUTDOWN) += oplus_bsp_dfr_force_shutdown.o
oplus_bsp_dfr_force_shutdown-y := force_shutdown.o
