# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_QCOM_PMICWD) += oplus_bsp_dfr_pmic_watchdog.o
oplus_bsp_dfr_pmic_watchdog-y := qcom_pmicwd.o qcom_pwkpwr.o
