# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2022-2030 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_COMBKEY_MONITOR) += oplus_bsp_dfr_combkey_monitor.o
oplus_bsp_dfr_combkey_monitor-y := combkey_monitor.o
