# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_HUNG_TASK_ENHANCE) += oplus_bsp_dfr_hung_task_enhance.o
oplus_bsp_dfr_hung_task_enhance-y := hung_task_enhance.o
