# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_OPLUS_FEATURE_GAME_OPT) += oplus_bsp_game_opt.o
oplus_bsp_game_opt-y := cpufreq_limits.o cpu_load.o fake_cpufreq.o game_ctrl.o rt_info.o task_util.o
