# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_SHUTDOWN_DETECT) += oplus_bsp_dfr_shutdown_detect.o
oplus_bsp_dfr_shutdown_detect-y := shutdown_detect.o
