# SPDX-License-Identifier: GPL-2.0

ifeq ($(CONFIG_OPLUS_SYSTEM_KERNEL_QCOM),y)
ccflags-y += -DCFG_OPLUS_ARCH_IS_QCOM
else
ccflags-y += -DCFG_OPLUS_ARCH_IS_MTK
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/2.0/core
endif

obj-$(CONFIG_PSEUDO_SENSOR) += pseudo_sensor.o
