# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2022-2030 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_KEYEVENT_HANDLER) += oplus_bsp_dfr_keyevent_handler.o
oplus_bsp_dfr_keyevent_handler-y := keyevent_handler.o
