# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_SAUPWK) += saupwk.o
obj-$(CONFIG_OPLUS_FEATURE_OPLUSBOOT) += oplusboot.o
obj-$(CONFIG_OPLUS_FEATURE_FTMMODE) 	+= oplus_ftm_mode.o
obj-$(CONFIG_OPLUS_FEATURE_CHARGERPRESENT) 	+= oplus_charger_present.o
obj-$(CONFIG_OPLUS_FEATURE_BUILDVARIANT) 	+= buildvariant.o
obj-$(CONFIG_OPLUS_FEATURE_CDT)	+= cdt_integrity.o
obj-$(CONFIG_OPLUS_FEATURE_SHUTDOWN_SPEED)	+= oplus_bsp_dfr_shutdown_speed.o
oplus_bsp_dfr_shutdown_speed-y := shutdown_speed.o
obj-$(CONFIG_OPLUS_FEATURE_BOOTARGS) += oplus_bootargs.o
